import './style.css'

type Point = { x: number; y: number }
type Barcode = { format: string; rawValue?: string; boundingBox?: DOMRect; cornerPoints?: Point[] }
type BarcodeDetectorLike = { detect(source: ImageBitmapSource): Promise<Barcode[]> }
type BarcodeDetectorConstructor = {
  new (options?: { formats?: string[] }): BarcodeDetectorLike
  getSupportedFormats(): Promise<string[]>
}

declare global { interface Window { BarcodeDetector?: BarcodeDetectorConstructor } }

const app = document.querySelector<HTMLDivElement>('#app')!
app.innerHTML = `
  <main><header><h1>Code 39 BarcodeDetector 検証</h1><p class="muted">ブラウザ標準APIの認識性能を確認する実験用ツール</p></header>
  <section class="status"><span id="cameraStatus">● Camera: stopped</span><span id="apiStatus">● BarcodeDetector: checking</span><span id="supportStatus">● Code 39: checking</span><span id="detectStatus">● Detecting: idle</span></section>
  <section class="toolbar"><button id="start">Start Camera</button><button id="stop" disabled>Stop Camera</button><label class="file">Select Image<input id="image" type="file" accept="image/*"></label><button id="clear">Clear Log</button></section>
  <div id="error" class="error" hidden></div>
  <section class="workspace"><div class="camera-container"><video id="video" autoplay playsinline muted></video><canvas id="overlay"></canvas><div id="found" class="found" hidden></div></div><aside><h2>Statistics</h2><dl><dt>Camera</dt><dd id="resolution">—</dd><dt>Camera FPS</dt><dd id="cameraFps">—</dd><dt>Detection FPS</dt><dd id="detectionFps">—</dd><dt>Detection latency</dt><dd id="latency">—</dd><dt>Last detection</dt><dd id="lastAgo">—</dd><dt>Detections</dt><dd id="count">0</dd><dt>Last result</dt><dd id="lastResult">—</dd></dl><h2>Recognition log</h2><pre id="log">No detections yet.</pre><p class="hint">テスト用Code 39は、対応するバーコード生成サイトで「Code 39」を選び、例: <code>*CUC12345*</code>（多くの生成器では文字列のみ入力）を作成してください。</p></aside></section>
  </main>`

const $ = <T extends HTMLElement>(id: string) => document.getElementById(id) as T
const video = $('video') as HTMLVideoElement, canvas = $('overlay') as HTMLCanvasElement, ctx = canvas.getContext('2d')!
const error = $('error'), detectorStatus = $('apiStatus'), supportStatus = $('supportStatus')
let detector: BarcodeDetectorLike | null = null, stream: MediaStream | null = null, running = false, busy = false
let frameCount = 0, detectionCount = 0, totalDetections = 0, lastFrameTime = performance.now(), lastDetectionAt = 0, lastLogValue = ''
let cameraFps = 0, detectionFps = 0, fpsWindow = performance.now(), windowFrames = 0, windowDetections = 0

function showError(message: string) { error.textContent = message; error.hidden = false }
function setText(id: string, value: string) { $(id).textContent = value }
function resizeCanvas() { canvas.width = video.videoWidth || 640; canvas.height = video.videoHeight || 480; canvas.style.aspectRatio = `${canvas.width}/${canvas.height}`; setText('resolution', `${canvas.width} × ${canvas.height}`) }
function draw(results: Barcode[]) { ctx.clearRect(0, 0, canvas.width, canvas.height); ctx.lineWidth = Math.max(3, canvas.width / 400); ctx.font = `${Math.max(16, canvas.width / 45)}px sans-serif`; results.forEach((b, i) => { const box = b.boundingBox; const pts = b.cornerPoints; ctx.strokeStyle = '#39ff88'; ctx.fillStyle = '#39ff88'; if (box) ctx.strokeRect(box.x, box.y, box.width, box.height); else if (pts?.length) { ctx.beginPath(); ctx.moveTo(pts[0].x, pts[0].y); pts.slice(1).forEach(p => ctx.lineTo(p.x, p.y)); ctx.closePath(); ctx.stroke() } const value = b.rawValue || '(no value)'; const x = box?.x ?? pts?.[0]?.x ?? 8, y = box?.y ?? pts?.[0]?.y ?? 24; ctx.fillText(value, x, Math.max(20, y - 8 + i * 20)) }) }
function addLog(value: string) { const now = performance.now(); if (value === lastLogValue && now - lastDetectionAt < 1000) return; lastLogValue = value; const line = `${new Date().toLocaleTimeString('ja-JP', { hour12: false })}.${String(new Date().getMilliseconds()).padStart(3, '0')}  ${value}`; const el = $('log'); el.textContent = (el.textContent === 'No detections yet.' ? '' : el.textContent + '\n') + line; el.scrollTop = el.scrollHeight }
async function detect() { if (!detector || busy || !running) return; busy = true; const started = performance.now(); try { const results = await detector.detect(video); setText('latency', `${(performance.now() - started).toFixed(1)} ms`); detectionCount++; windowDetections++; totalDetections += results.length; setText('count', String(totalDetections)); draw(results); if (results.length) { const value = results[0].rawValue || '(no value)'; lastDetectionAt = performance.now(); setText('lastResult', `${results[0].format}: ${value}`); $('found').textContent = `FOUND: ${value}`; $('found').hidden = false; addLog(value) } else $('found').hidden = true } catch (e) { showError(`BarcodeDetector.detect() に失敗しました: ${e instanceof Error ? e.message : String(e)}`) } finally { busy = false } }
function frame(now: number) { if (!running) return; frameCount++; windowFrames++; if (now - fpsWindow >= 1000) { cameraFps = windowFrames * 1000 / (now - fpsWindow); detectionFps = windowDetections * 1000 / (now - fpsWindow); setText('cameraFps', cameraFps.toFixed(1)); setText('detectionFps', detectionFps.toFixed(1)); windowFrames = windowDetections = 0; fpsWindow = now } if (now - lastFrameTime >= 75) { lastFrameTime = now; void detect() } if (lastDetectionAt) setText('lastAgo', `${Math.round(now - lastDetectionAt)} ms ago`); requestAnimationFrame(frame) }
async function startCamera() { if (!detector) return; showError(''); error.hidden = true; try { stream = await navigator.mediaDevices.getUserMedia({ video: { facingMode: { ideal: 'environment' }, width: { ideal: 1920 }, height: { ideal: 1080 } }, audio: false }); video.srcObject = stream; await video.play(); resizeCanvas(); running = true; $('start').setAttribute('disabled', 'true'); $('stop').removeAttribute('disabled'); setText('cameraStatus', '● Camera: running'); setText('detectStatus', '● Detecting: active'); requestAnimationFrame(frame) } catch (e) { showError(`カメラを開始できませんでした。HTTPSまたはlocalhostで実行し、カメラ権限を確認してください。\n${e instanceof Error ? e.message : String(e)}`) } }
function stopCamera() { running = false; stream?.getTracks().forEach(t => t.stop()); stream = null; video.srcObject = null; ctx.clearRect(0, 0, canvas.width, canvas.height); $('start').removeAttribute('disabled'); $('stop').setAttribute('disabled', 'true'); setText('cameraStatus', '● Camera: stopped'); setText('detectStatus', '● Detecting: idle') }
async function init() { if (!window.BarcodeDetector) { detectorStatus.textContent = '● BarcodeDetector: unavailable'; showError('このブラウザでは BarcodeDetector API が利用できません。'); return } detectorStatus.textContent = '● BarcodeDetector: available'; try { const supported = await window.BarcodeDetector.getSupportedFormats(); if (!supported.includes('code_39')) { supportStatus.textContent = '● Code 39: unsupported'; showError('このブラウザ/環境では BarcodeDetector の Code 39 に対応していません。'); return } supportStatus.textContent = '● Code 39: supported'; detector = new window.BarcodeDetector({ formats: ['code_39'] }) } catch (e) { showError(`BarcodeDetector の初期化に失敗しました: ${String(e)}`) } }
$('start').addEventListener('click', () => void startCamera()); $('stop').addEventListener('click', stopCamera); $('clear').addEventListener('click', () => { $('log').textContent = 'No detections yet.'; lastLogValue = '' }); video.addEventListener('loadedmetadata', resizeCanvas); window.addEventListener('resize', resizeCanvas)
$('image').addEventListener('change', async (event) => { const file = (event.target as HTMLInputElement).files?.[0]; if (!file || !detector) return; const image = new Image(); image.onload = async () => { canvas.width = image.naturalWidth; canvas.height = image.naturalHeight; ctx.clearRect(0, 0, canvas.width, canvas.height); try { const started = performance.now(); const results = await detector!.detect(image); setText('latency', `${(performance.now() - started).toFixed(1)} ms`); draw(results); setText('count', String(results.length)); setText('lastResult', results[0] ? `${results[0].format}: ${results[0].rawValue || '(no value)'}` : '—'); results.forEach(r => addLog(r.rawValue || '(no value)')); } catch (e) { showError(`画像の解析に失敗しました: ${String(e)}`) } }; image.src = URL.createObjectURL(file) })
void init()
